### ISSUE TITLE
关于下载问题

### ISSUE THREAD

**Issue by ShCby** [CJReinforce/PikPakAutoOfflineDownloadBot#19]
pikpak支持ed2k等链接的下载但是为什么bot只支持magnet呢？

**Comment by ShCby** [comment]
@CJReinforce @huanity

**Comment by huanity** [comment]
因为设计之初只考虑了下载磁力链接，默认只能识别磁力链接

**Comment by huanity** [comment]
fork项目已支持普通链接的下载，使用 `/p` 命令触发，感谢 @qiqiandfei 提供的代码支持
https://github.com/huanity/PikPakAutoOfflineDownloadBot
