### ISSUE TITLE
0.0.2总是Aria2离线下载到本地失败

### ISSUE THREAD

**Issue by zq500480** [CJReinforce/PikPakAutoOfflineDownloadBot#21]
1、已经配置好aria2地址和端口，本地也可以正常访问，  但是总无法离线到NAS
2、aria2 / bot全部在一台NAS安装
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/34306818/225243853-ba1a120c-043e-41f8-b55d-5790a5bc2c83.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/34306818/225243883-bd3a47a5-c63a-486e-b656-f78382271e4c.png">

**Comment by zq500480** [comment]
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/34306818/225244186-89021385-b657-419c-80b6-1b4b97794a68.png">

**Comment by yunnl** [comment]
ip不需要带http://，直接填写ip地址就行
