### ISSUE TITLE
pik官方修改登录接口导致无法登录

### ISSUE THREAD

**Issue by uclinch** [CJReinforce/PikPakAutoOfflineDownloadBot#25]
20240522
`pikpak官方为了更新 google oauth2 协议规范，进行修改了登录api接口，第三方客户端退出登录后将会无法再次登录，已登录用户不受影响
现在有手动登录方法，打开官网正常进行登录，然后按下F12打开网络筛选器搜索 https://api-drive.mypikpak.com/vip/v1/vip/info ，请求头部里面 Authorization 字段的所有内容复制到 pikpak_config.ini 文件的 access_token 参数里面，第三方客户端就能登录上了`

以上是pik群里看到的。

现在咱们的bot无法登录，所以没法用了。希望up帮忙修复一下。

**Comment by huanity** [comment]
已尝试修复，详见 #26

**Comment by huanity** [comment]
> 20240522 `pikpak官方为了更新 google oauth2 协议规范，进行修改了登录api接口，第三方客户端退出登录后将会无法再次登录，已登录用户不受影响 现在有手动登录方法，打开官网正常进行登录，然后按下F12打开网络筛选器搜索 https://api-drive.mypikpak.com/vip/v1/vip/info ，请求头部里面 Authorization 字段的所有内容复制到 pikpak_config.ini 文件的 access_token 参数里面，第三方客户端就能登录上了`
> 
> 以上是pik群里看到的。
> 
> 现在咱们的bot无法登录，所以没法用了。希望up帮忙修复一下。

已尝试修复，详见 #26
