### ISSUE TITLE
如果文件夹里的电视剧有10集，每集2.5GB，这个能不能帮我自动下载前两集，下载完后自动删除，然后依次每次下载两集呢？

### ISSUE THREAD

**Issue by trunghuyne** [CJReinforce/PikPakAutoOfflineDownloadBot#35]
如果文件夹里的电视剧有10集，每集2.5GB，这个能不能帮我自动下载前两集，下载完后自动删除，然后依次每次下载两集呢？
thanks!

**Comment by huanity** [comment]
很好的想法，但是无法做到，离线的原理是将磁力文件一次性离线到云盘，是无法将磁力中的内容分开来离线的，所以无法突破云盘空间的限制，如果有需求可以购买pikpak会员，今天应该是最后一天优惠折扣，祝好。
